### ISSUE TITLE
Dependency Mod is dysfunctional for 1.20.1

### ISSUE THREAD

**Issue by Tsunai001** [Chailotl/particular#29]
[2024-06-18 16:47:09.420] [info]  [16:46:33] [WARN] [FabricLoader/Metadata]: The mod "sushi_bar" contains invalid entries in its mod json:
[2024-06-18 16:47:09.421] [info]  - Unsupported root entry "plugin" at line 42 column 11

Using sushi bar 0.1.0 but same result for every single version. using all dependencies including owo. ver 1.20.1

**Comment by Chailotl** [comment]
Can you please send the entire log via [mclo.gs](https://mclo.gs/)?

**Comment by Chailotl** [comment]
Scratch that, I've identified the issue, and it's bizarre that this didn't show up when testing in both dev and prod and just worked fine. A fix will be pushed very soon

**Comment by Tsunai001** [comment]
> Scratch that, I've identified the issue, and it's bizarre that this didn't show up when testing in both dev and prod and just worked fine. A fix will be pushed very soon

thats awesome, i was super exited to try this mod as effective aint for 1.20 bc they stink so glad someone understands how important those features are, (on top of the unique features your mod adds bc it aint just the effective stuff) anyways, just an fyi, i am using lunar client so its extra sensitive although these are logs from .minecraft crash reports and not lunar logs, regardless its actually awesome that it said the exact line and column of the code making it easier on u.

**Comment by Chailotl** [comment]
This has been fixed now with 0.2.1!

**Comment by Tsunai001** [comment]
[2104e6ad-f6dc-42a9-aba1-06a1cf915b10-voicetesting.log](https://github.com/user-attachments/files/15899089/2104e6ad-f6dc-42a9-aba1-06a1cf915b10-voicetesting.log)
Its still crashing, are you able to take a look at my logs please

**Comment by Chailotl** [comment]
There is zero mention of Particular or Sushi Bar in this log, are you sure this has to do with my mods?

**Comment by Tsunai001** [comment]
must be a lunar only issue then
