### ISSUE TITLE
Cascades don't work on servers :(( they are very buggyyy

### ISSUE THREAD

**Issue by DEIVICHII** [Chailotl/particular#44]
https://github.com/user-attachments/assets/c306931b-b5af-49f0-963e-94fdb2866a05

I absolutely adore this mod, please let there be a fix bc my base needs it's dragon waterfall :(((

**Comment by ThexXTURBOXx** [comment]
This already has a fix available: https://github.com/Chailotl/particular/pull/36

Aaand this is also the same as #6

**Comment by Cmac21798** [comment]
> This already has a fix available: [#36](https://github.com/Chailotl/particular/pull/36)
> 
> Aaand this is also the same as [#6](https://github.com/Chailotl/particular/issues/6)

How would I install this fix? Using the most recent version of Particulate (which is this mod but updated for the most recent version of MC), and the bug with cascades on multiplayer is still happening
